In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Lambda, Flatten
from keras.layers import Convolution1D, Dense, Dropout, MaxPooling1D, LSTM
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from keras import callbacks
from keras.callbacks import CSVLogger
from keras.utils import to_categorical
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger
from sklearn.dummy import DummyClassifier
from sklearn.preprocessing import StandardScaler
import pickle
from sklearn import metrics
from sklearn.metrics import f1_score
import matplotlib.pyplot as plt
import seaborn as sns
import pandas  as pd
import numpy as np
import os
import time
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
        f1_score, classification_report,
        confusion_matrix, roc_curve,
        roc_auc_score, accuracy_score,
        log_loss)
from sklearn import __version__ as sklearn_version
from sklearn.neighbors import KNeighborsClassifier
from imblearn.under_sampling import NearMiss
from datetime import datetime
np.random.seed(0)

In [3]:
dir2='/content/drive/MyDrive/8thSemProject/botnet_dataset/device4/'
device2_df=pd.DataFrame()
i=0
for file in os.listdir(dir2+'gafgyt/'):
  df_file = pd.read_csv(os.path.join(dir2+'gafgyt/', file), encoding = 'ISO-8859-1',low_memory=False)
  df_file["label"]=i
  i=i+1
  device2_df=pd.concat([device2_df, df_file])
for file in os.listdir(dir2+'mirai/'):
  df_file = pd.read_csv(os.path.join(dir2+'mirai/', file), encoding = 'ISO-8859-1',low_memory=False)
  df_file["label"]=i
  i=i+1
  device2_df=pd.concat([device2_df, df_file])
df_file=pd.read_csv('/content/drive/MyDrive/8thSemProject/botnet_dataset/device4/benign.csv')
df_file['label']=i
device2_df=pd.concat([device2_df, df_file])

In [4]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(device2_df, test_size=0.2)


In [5]:
X_train=train.drop(['label'],axis=1)
y_train=train['label']


In [6]:
from sklearn.tree import DecisionTreeClassifier
model_lr=DecisionTreeClassifier()
rfe = RFE(model_lr, n_features_to_select=50,step=4)
rfe.fit(X_train,y_train)

RFE(estimator=DecisionTreeClassifier(), n_features_to_select=50, step=4)

In [7]:
from operator import itemgetter
features = X_train.columns.to_list()
i=0
feat_arr_rem=[]
for x, y in (sorted(zip(rfe.ranking_ , features), key=itemgetter(0))):
    if(x!=1):
      i=i+1
      feat_arr_rem.append(y)

In [8]:
mod_df=device2_df.copy()
for str in feat_arr_rem:
  if(str=='label'):
    continue
  mod_df.drop([str],axis=1, inplace=True)
mod_df.head()

MI_dir_L1_weight  MI_dir_L1_mean  MI_dir_L1_variance  MI_dir_L0.1_weight  \
0          1.000000       98.000000        0.000000e+00            1.000000   
1          1.492583       98.000000        3.637979e-12            1.931640   
2          2.294102       84.051188        2.517926e+02            2.904273   
3          3.280499       80.987267        1.964467e+02            3.902546   
4          4.280490       79.354915        1.592943e+02            4.902545   

   MI_dir_L0.1_mean  MI_dir_L0.1_variance  MI_dir_L0.01_weight  \
0         98.000000          0.000000e+00             1.000000   
1         98.000000          1.818989e-12             1.992944   
2         86.981750          2.311822e+02             2.990102   
3         83.655268          2.040614e+02             3.989925   
4         81.685828          1.775746e+02             4.989924   

   MI_dir_L0.01_mean  MI_dir_L0.01_variance  H_L5_mean  ...  HpHp_L0.1_radius  \
0          98.000000               0.000000  98.000000  ...      0.000000e+00   
1          98.000000               0.000000  98.000000  ...      1.818989e-12   
2          87.298025             227.930928  76.725612  ...      0.000000e+00   
3          83.965124             204.017078  75.617679  ...      0.000000e+00   
4          81.968075             179.043909  75.150149  ...      0.000000e+00   

   HpHp_L0.1_covariance  HpHp_L0.1_pcc  HpHp_L0.01_weight  HpHp_L0.01_mean  \
0                   0.0            0.0           1.000000             98.0   
1                   0.0            0.0           1.992944             98.0   
2                   0.0            0.0           1.000000             66.0   
3                   0.0            0.0           1.000000             74.0   
4                   0.0            0.0           1.000000             74.0   

   HpHp_L0.01_std  HpHp_L0.01_magnitude  HpHp_L0.01_radius  \
0        0.000000             98.000000       0.000000e+00   
1        0.000001            138.592929       1.818989e-12   
2        0.000000            114.856432       0.000000e+00   
3        0.000000             74.000000       0.000000e+00   
4        0.000000             74.000000       0.000000e+00   

   HpHp_L0.01_covariance  label  
0                    0.0      0  
1                    0.0      0  
2                    0.0      0  
3                    0.0      0  
4                    0.0      0  

[5 rows x 51 columns]

In [9]:
mod_df.to_csv('/content/drive/MyDrive/8thSemProject/botnet_dataset/device4/dataset_final.csv')

In [10]:
temp_df=pd.read_csv('/content/drive/MyDrive/8thSemProject/botnet_dataset/device4/dataset_final.csv')

In [11]:
x=temp_df.drop(['label'],axis=1)
y=temp_df['label']
normalized_df=(x-x.mean())/x.std()
y.head()

0    0
1    0
2    0
3    0
4    0
Name: label, dtype: int64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(normalized_df, y, test_size=0.2, random_state=0)
y_train = np.array(y_train)

y_train = np.array(y_train)
y_test = np.array(y_test)
X_train = np.array(X_train)
X_test = np.array(X_test)
X_train = np.reshape(X_train, (X_train.shape[0],X_train.shape[1]))
X_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1]))
print('xtrain={}, ytrain={}, xtest={}, ytest={}'.format(X_train.shape,y_train.shape,X_test.shape,y_test.shape))

xtrain=(878941, 51), ytrain=(878941,), xtest=(219736, 51), ytest=(219736,)


In [13]:
!pip install xgboost

In [14]:
from xgboost import XGBClassifier
model = XGBClassifier()
start=time.time()
model.fit(X_train, y_train)
end=time.time()
tt=end-start

In [15]:
y_pred=model.predict(X_test)

In [16]:
y_train.shape

(878941,)

In [17]:
from sklearn import metrics
from sklearn.metrics import f1_score
print('XGBoost Classifier')
print(f"Training time: {tt}s")
print('Accuracy = ', metrics.accuracy_score(y_test, y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None,
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred,
                                                                 labels=None,
                                                                 target_names=None,
                                                                 sample_weight=None,
                                                                 digits=2,
                                                                 output_dict=False))

print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

XGBoost Classifier
Training time: 196.67898797988892s
Accuracy =  99.99772454217789
Confusion Matrix =
 [[11558     0     0     0     0     0     0     0     0     0     0]
 [    2  5606     0     0     0     0     0     0     0     0     0]
 [    0     1  5465     0     0     0     0     0     0     0     0]
 [    1     0     1 18436     0     0     0     0     0     0     0]
 [    0     0     0     0 21132     0     0     0     0     0     0]
 [    0     0     0     0     0 18333     0     0     0     0     0]
 [    0     0     0     0     0     0 20886     0     0     0     0]
 [    0     0     0     0     0     0     0 23755     0     0     0]
 [    0     0     0     0     0     0     0     0 43381     0     0]
 [    0     0     0     0     0     0     0     0     0 16325     0]
 [    0     0     0     0     0     0     0     0     0     0 34854]]
Recall = 0.9999772454217789
Classification Report =
               precision    recall  f1-score   support

           0       1.00     

In [18]:
from sklearn.ensemble import RandomForestClassifier
def rf_classifier(data, device_name, scaling=False,):
    X = data.drop(['label'], axis=1)
    y = data['label']
    print(f'Original Shape:{X.shape}, {y.shape}')
    if scaling == False:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=47)
        model_name = f'{device_name}_without_scaling_unbalanced_model.pkl'
    else:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=47)
        scaler = StandardScaler()
        scaler.fit(X_train)
        X_train = scaler.transform(X_train)
        X_test = scaler.transform(X_test)
        model_name = f'{device_name}_with_scaling_unbalanced_model.pkl'

    clf = RandomForestClassifier()
    start=time.time()
    model_res = clf.fit(X_train, y_train)
    end=time.time()
    tt=end-start
    y_pred = model_res.predict(X_test)
    y_pred_prob = model_res.predict_proba(X_test)
    lr_probs = y_pred_prob[:,1]
    ac = accuracy_score(y_test, y_pred)
    importances = pd.DataFrame({'feature':X.columns,'importance':np.round(clf.feature_importances_,3)})
    importances = importances.sort_values('importance',ascending=False).set_index('feature')

    f1 = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)
    print("Random Forest Classifier")
    print(f"Training time: {tt}s")
    print('Accuracy=%.3f' % (ac))
    print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
    print('f1-score=%.3f' % (f1))
    print('Confusion Matrix = \n', cm)
    print('Classification Report = \n',classification_report(y_test, y_pred))

In [19]:
rf_classifier(temp_df,'device4',True)

Original Shape:(1098677, 51), (1098677,)
Random Forest Classifier
Training time: 310.25970792770386s
Accuracy=0.916
Recall = 0.9162540503149234
f1-score=0.887
Confusion Matrix = 
 [[17564     1     0     0     0     0     0     0     0     0     0]
 [    0  8561     0     0     1     0     0     0     0     0     0]
 [    1     0  8325     1     0     0     0     0     0     0     0]
 [    0     1     0    28 27587     0     0     0     0     0     2]
 [    0     0     0     0 31734     0     0     0     0     0     7]
 [    0     0     0     0     0 27357     0     0     0     0     0]
 [    0     0     0     0     0     0 30965     0     0     0     1]
 [    0     0     0     0     0     0     0 35635     0     0     0]
 [    0     0     0     0     1     0     0     0 64877     0     0]
 [    0     0     0     0     0     0     0     0     0 24289     0]
 [    0     0     0     0     0     0     0     0     0     0 52666]]
Classification Report = 
               precision    recall 

In [20]:
from sklearn import metrics
from sklearn.metrics import f1_score
def knn_classifier_unbalanced(data, scaling=False):
    X = data.drop(['label'], axis=1)
    y = data['label']
    print(f'Original Shape:{X.shape}, {y.shape}')
    test_scores = []
    train_scores = []
    error = []
    if scaling == False:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=47)
    else:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=47)
        scaler = StandardScaler()
        scaler.fit(X_train)
        X_train = scaler.transform(X_train)
        X_test = scaler.transform(X_test)

    knn = KNeighborsClassifier(3)
    start=time.time()
    knn.fit(X_train,y_train)
    end=time.time()
    tt=end-start
    y_pred = knn.predict(X_test)
    error.append(np.mean(y_pred != y_test))
    train_scores.append(knn.score(X_train,y_train))
    test_scores.append(knn.score(X_test,y_test))
    print("KNN")
    print(f"Training time: {tt}s")
    print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
    print('Classification Report = \n',classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print(f'Accuracy on Training set:{train_scores}')
    print(f'Accuracy on Test set:{test_scores}')

In [ ]:
knn_classifier_unbalanced(temp_df,True)

Original Shape:(1098677, 51), (1098677,)


In [ ]:
def dt_classifier(data, device_name, scaling=False,):
    X = data.drop(['label'], axis=1)
    y = data['label']
    print(f'Original Shape:{X.shape}, {y.shape}')
    if scaling == False:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=47)
        model_name = f'{device_name}_without_scaling_unbalanced_model_decision_tree_gini.pkl'
    else:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=47)
        scaler = StandardScaler()
        scaler.fit(X_train)
        X_train = scaler.transform(X_train)
        X_test = scaler.transform(X_test)
        model_name = f'{device_name}_with_scaling_unbalanced_model_decision_tree_gini.pkl'

    clf = DecisionTreeClassifier(criterion='gini', random_state= 1234, max_depth  = 5 )
    start=time.time()
    model_res = clf.fit(X_train, y_train)
    end=time.time()
    tt=end-start
    y_pred = model_res.predict(X_test)
    y_pred_prob = model_res.predict_proba(X_test)
    lr_probs = y_pred_prob[:,1]
    ac = accuracy_score(y_test, y_pred)
    importances = pd.DataFrame({'feature':X.columns,'importance':np.round(clf.feature_importances_,3)})
    importances = importances.sort_values('importance',ascending=False).set_index('feature')
    f1 = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)
    print('Decision tree')
    print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
    print(f"Training time: {tt}s")
    print('Accuracy=%.3f' % (ac))
    print('f1-score=%.3f' % (f1))
    print('Confusion Matrix = \n', cm)
    print('Classification Report',classification_report(y_test, y_pred))

In [ ]:
dt_classifier(temp_df,'device2',True)