In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Lambda, Flatten
from keras.layers import Convolution1D, Dense, Dropout, MaxPooling1D, LSTM
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from keras import callbacks
from keras.callbacks import CSVLogger
from keras.utils import to_categorical
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger
from sklearn.dummy import DummyClassifier
from sklearn.preprocessing import StandardScaler 
import pickle
from sklearn import metrics
from sklearn.metrics import f1_score
import matplotlib.pyplot as plt
import seaborn as sns
import pandas  as pd
import numpy as np
import os
import time
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
        f1_score, classification_report, 
        confusion_matrix, roc_curve, 
        roc_auc_score, accuracy_score,
        log_loss)
from sklearn import __version__ as sklearn_version
from sklearn.neighbors import KNeighborsClassifier
from imblearn.under_sampling import NearMiss
from datetime import datetime
np.random.seed(0)

In [ ]:
dir2='/content/drive/MyDrive/botnet_dataset/device9/'
device2_df=pd.DataFrame()
i=0
for file in os.listdir(dir2+'gafgyt/'):
  df_file = pd.read_csv(os.path.join(dir2+'gafgyt/', file), encoding = 'ISO-8859-1',low_memory=False)
  df_file["label"]=i
  i=i+1
  device2_df=pd.concat([device2_df, df_file])
for file in os.listdir(dir2+'mirai/'):
  df_file = pd.read_csv(os.path.join(dir2+'mirai/', file), encoding = 'ISO-8859-1',low_memory=False)
  df_file["label"]=i
  i=i+1
  device2_df=pd.concat([device2_df, df_file])
df_file=pd.read_csv('/content/drive/MyDrive/botnet_dataset/device9/benign.csv')
df_file['label']=i
device2_df=pd.concat([device2_df, df_file])

In [ ]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(device2_df, test_size=0.2)


In [ ]:
X_train=train.drop(['label'],axis=1)
y_train=train['label']


In [ ]:
from sklearn.tree import DecisionTreeClassifier
model_lr=DecisionTreeClassifier()
rfe = RFE(model_lr, n_features_to_select=50,step=4)
rfe.fit(X_train,y_train)

RFE(estimator=DecisionTreeClassifier(), n_features_to_select=50, step=4)

In [ ]:
from operator import itemgetter
features = X_train.columns.to_list()
i=0
feat_arr_rem=[]
for x, y in (sorted(zip(rfe.ranking_ , features), key=itemgetter(0))):
    if(x!=1):
      i=i+1
      feat_arr_rem.append(y)

In [ ]:
mod_df=device2_df.copy()
for str in feat_arr_rem:
  if(str=='label'):
    continue
  mod_df.drop([str],axis=1, inplace=True)
mod_df.head()

MI_dir_L1_weight  MI_dir_L1_mean  MI_dir_L1_variance  MI_dir_L0.1_weight  \
0          1.000000       98.000000        0.000000e+00            1.000000   
1          1.492583       98.000000        3.637979e-12            1.931640   
2          2.294102       84.051188        2.517926e+02            2.904273   
3          3.280499       80.987267        1.964467e+02            3.902546   
4          4.280490       79.354915        1.592943e+02            4.902545   

   MI_dir_L0.1_mean  MI_dir_L0.1_variance  MI_dir_L0.01_weight  \
0         98.000000          0.000000e+00             1.000000   
1         98.000000          1.818989e-12             1.992944   
2         86.981750          2.311822e+02             2.990102   
3         83.655268          2.040614e+02             3.989925   
4         81.685828          1.775746e+02             4.989924   

   MI_dir_L0.01_mean  MI_dir_L0.01_variance  H_L5_weight  ...  HpHp_L3_pcc  \
0          98.000000               0.000000     1.000000  ...          0.0   
1          98.000000               0.000000     1.029000  ...          0.0   
2          87.298025             227.930928     1.504156  ...          0.0   
3          83.965124             204.017078     2.460087  ...          0.0   
4          81.968075             179.043909     3.460055  ...          0.0   

   HpHp_L1_mean  HpHp_L1_std  HpHp_L1_magnitude  HpHp_L1_pcc  \
0          98.0     0.000000          98.000000          0.0   
1          98.0     0.000002         138.592929          0.0   
2          66.0     0.000000         114.856432          0.0   
3          74.0     0.000000          74.000000          0.0   
4          74.0     0.000000          74.000000          0.0   

   HpHp_L0.1_weight  HpHp_L0.1_mean  HpHp_L0.1_std  HpHp_L0.1_magnitude  label  
0           1.00000            98.0       0.000000            98.000000      0  
1           1.93164            98.0       0.000001           138.592929      0  
2           1.00000            66.0       0.000000           114.856432      0  
3           1.00000            74.0       0.000000            74.000000      0  
4           1.00000            74.0       0.000000            74.000000      0  

[5 rows x 51 columns]

In [ ]:
mod_df.to_csv('/content/drive/MyDrive/botnet_dataset/device9/dataset_final.csv')

In [3]:
temp_df=pd.read_csv('/content/drive/MyDrive/botnet_dataset/device9/dataset_final.csv')

In [ ]:
x=temp_df.drop(['label'],axis=1)
y=temp_df['label']
normalized_df=(x-x.mean())/x.std()
y.head()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(normalized_df, y, test_size=0.2, random_state=0)
y_train = np.array(y_train)

y_train = np.array(y_train)
y_test = np.array(y_test)
X_train = np.array(X_train)
X_test = np.array(X_test)
X_train = np.reshape(X_train, (X_train.shape[0],X_train.shape[1]))
X_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1]))
print('xtrain={}, ytrain={}, xtest={}, ytest={}'.format(X_train.shape,y_train.shape,X_test.shape,y_test.shape))

In [ ]:
!pip install xgboost

In [ ]:
from xgboost import XGBClassifier
model = XGBClassifier()
start=time.time()
model.fit(X_train, y_train)
end=time.time()
tt=end-start

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
y_train.shape

(680660,)

In [ ]:
from sklearn import metrics
from sklearn.metrics import f1_score
print('XGBoost Classifier')
print(f"Training time: {tt}s")
print('Accuracy = ', metrics.accuracy_score(y_test, y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                 digits=2, 
                                                                 output_dict=False))

print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

XGBoost Classifier
Training time: 2090.3921897411346s
Accuracy =  99.99764935416006
Confusion Matrix =
 [[12066     2     0     0     0     0     0     0     0     0     0]
 [    1  5343     0     0     0     0     0     0     0     0     0]
 [    0     0  5779     0     0     0     0     0     0     0     0]
 [    0     0     0 19491     0     0     0     0     0     0     0]
 [    0     0     0     0 20649     0     0     0     0     0     0]
 [    0     0     0     0     0 21606     0     0     0     0     0]
 [    0     0     0     0     0     0  8827     0     0     0     0]
 [    0     0     0     0     0     0     0 24328     0     0     0]
 [    0     0     0     0     0     1     0     0 31500     0     0]
 [    0     0     0     0     0     0     0     0     0 16743     0]
 [    0     0     0     0     0     0     0     0     0     0  3830]]
Recall = 0.9999764935416006
Classification Report =
               precision    recall  f1-score   support

           0       1.00     

In [ ]:
from sklearn.ensemble import RandomForestClassifier
def rf_classifier(data, device_name, scaling=False,):
    X = data.drop(['label'], axis=1)
    y = data['label']
    print(f'Original Shape:{X.shape}, {y.shape}')
    if scaling == False:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=47)
        model_name = f'{device_name}_without_scaling_unbalanced_model.pkl'
    else:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=47)
        scaler = StandardScaler()
        scaler.fit(X_train)
        X_train = scaler.transform(X_train)
        X_test = scaler.transform(X_test)
        model_name = f'{device_name}_with_scaling_unbalanced_model.pkl'
    
    clf = RandomForestClassifier()
    start=time.time()
    model_res = clf.fit(X_train, y_train)
    end=time.time()
    tt=end-start
    y_pred = model_res.predict(X_test)
    y_pred_prob = model_res.predict_proba(X_test)
    lr_probs = y_pred_prob[:,1]
    ac = accuracy_score(y_test, y_pred)
    importances = pd.DataFrame({'feature':X.columns,'importance':np.round(clf.feature_importances_,3)})
    importances = importances.sort_values('importance',ascending=False).set_index('feature')

    f1 = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)
    print("Random Forest Classifier")
    print(f"Training time: {tt}s")
    print('Accuracy=%.3f' % (ac))
    print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
    print('f1-score=%.3f' % (f1))
    print('Confusion Matrix = \n', cm)
    print('Classification Report = \n',classification_report(y_test, y_pred))

In [ ]:
rf_classifier(temp_df,'device4',True)

Original Shape:(850826, 51), (850826,)
Random Forest Classifier
Training time: 230.96983122825623s
Accuracy=0.932
Recall = 0.9321522597630539
f1-score=0.925
Confusion Matrix = 
 [[17919     1     1     1     0     0     0     0     0     0     0]
 [    0  8178     0     1     0     0     0     0     0     0     0]
 [    0     1  8528     0     1     0     0     0     0     0     0]
 [    0     1     0 11980 17305     0     0     0     0     0     1]
 [    0     0     0     1 30601     0     0     0     0     0     0]
 [    0     0     0     0     0 32296     0     0     0     0     0]
 [    1     0     0     0     0     0 13067     0     0     0     1]
 [    0     0     0     0     0     0     0 36866     0     0     0]
 [    0     0     0     0     0     0     0     0 47177     0     0]
 [    0     0     0     0     0     0     0     0     0 25390     0]
 [    0     0     0     1     1     0     0     0     0     0  5928]]
Classification Report = 
               precision    recall  f

In [4]:
from sklearn import metrics
from sklearn.metrics import f1_score
def knn_classifier_unbalanced(data, scaling=False):
    X = data.drop(['label'], axis=1)
    y = data['label']
    print(f'Original Shape:{X.shape}, {y.shape}')
    test_scores = []
    train_scores = []
    error = []
    if scaling == False:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=47)
    else:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=47)
        scaler = StandardScaler()
        scaler.fit(X_train)
        X_train = scaler.transform(X_train)
        X_test = scaler.transform(X_test)
        
    knn = KNeighborsClassifier(3)
    start=time.time()
    knn.fit(X_train,y_train)
    end=time.time()
    tt=end-start
    y_pred = knn.predict(X_test)
    error.append(np.mean(y_pred != y_test))
    train_scores.append(knn.score(X_train,y_train))
    test_scores.append(knn.score(X_test,y_test))
    print("KNN")
    print(f"Training time: {tt}s")
    print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
    print("f1-score=",metrics.f1_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
    print('Classification Report = \n',classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print(f'Accuracy on Training set:{train_scores}')
    print(f'Accuracy on Test set:{test_scores}')

In [5]:
knn_classifier_unbalanced(temp_df,True)

Original Shape:(850826, 51), (850826,)
KNN
Training time: 0.26842737197875977s
Recall = 0.9041011095091832
f1-score= 0.9041027380881828
Classification Report = 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     17922
           1       1.00      1.00      1.00      8179
           2       1.00      1.00      1.00      8530
           3       0.58      0.58      0.58     29287
           4       0.60      0.60      0.60     30602
           5       1.00      1.00      1.00     32296
           6       1.00      1.00      1.00     13069
           7       1.00      1.00      1.00     36866
           8       1.00      1.00      1.00     47177
           9       1.00      1.00      1.00     25390
          10       1.00      1.00      1.00      5930

    accuracy                           0.90    255248
   macro avg       0.93      0.93      0.93    255248
weighted avg       0.90      0.90      0.90    255248

[[17905    10     4     0

In [ ]:
def dt_classifier(data, device_name, scaling=False,):
    X = data.drop(['label'], axis=1)
    y = data['label']
    print(f'Original Shape:{X.shape}, {y.shape}')
    if scaling == False:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=47)
        model_name = f'{device_name}_without_scaling_unbalanced_model_decision_tree_gini.pkl'
    else:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=47)
        scaler = StandardScaler()
        scaler.fit(X_train)
        X_train = scaler.transform(X_train)
        X_test = scaler.transform(X_test)
        model_name = f'{device_name}_with_scaling_unbalanced_model_decision_tree_gini.pkl'
    
    clf = DecisionTreeClassifier(criterion='gini', random_state= 1234, max_depth  = 5 )
    start=time.time()
    model_res = clf.fit(X_train, y_train)
    end=time.time()
    tt=end-start
    y_pred = model_res.predict(X_test)
    y_pred_prob = model_res.predict_proba(X_test)
    lr_probs = y_pred_prob[:,1]
    ac = accuracy_score(y_test, y_pred)
    importances = pd.DataFrame({'feature':X.columns,'importance':np.round(clf.feature_importances_,3)})
    importances = importances.sort_values('importance',ascending=False).set_index('feature')
    f1 = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)
    print('Decision tree')
    print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
    print(f"Training time: {tt}s")
    print('Accuracy=%.3f' % (ac))
    print('f1-score=%.3f' % (f1))
    print('Confusion Matrix = \n', cm)
    print('Classification Report',classification_report(y_test, y_pred))

In [ ]:
dt_classifier(temp_df,'device2',True)

Original Shape:(850826, 51), (850826,)
Decision tree
Recall = 0.8299418604651163
Training time: 15.743852138519287s
Accuracy=0.830
f1-score=0.770
Confusion Matrix = 
 [[17916     0     5     0     1     0     0     0     0     0     0]
 [ 8177     0     1     0     1     0     0     0     0     0     0]
 [    0     0  8528     0     2     0     0     0     0     0     0]
 [    0     0    35     6 29246     0     0     0     0     0     0]
 [    0     0    20     0 30582     0     0     0     0     0     0]
 [    0     0     0     0     0 32296     0     0     0     0     0]
 [    0     0     2     0     1     0 13065     0     0     0     1]
 [    0     0     0     0     0     0     0 36866     0     0     0]
 [    0     0     0     0     0     0     1     0 47176     0     0]
 [    0     0     0     0     0     0     0     0     0 25389     1]
 [    0     0  5911     0     2     0     0     0     0     0    17]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Classification Report               precision    recall  f1-score   support

           0       0.69      1.00      0.81     17922
           1       0.00      0.00      0.00      8179
           2       0.59      1.00      0.74      8530
           3       1.00      0.00      0.00     29287
           4       0.51      1.00      0.68     30602
           5       1.00      1.00      1.00     32296
           6       1.00      1.00      1.00     13069
           7       1.00      1.00      1.00     36866
           8       1.00      1.00      1.00     47177
           9       1.00      1.00      1.00     25390
          10       0.89      0.00      0.01      5930

    accuracy                           0.83    255248
   macro avg       0.79      0.73      0.66    255248
weighted avg       0.87      0.83      0.77    255248



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
