In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import time
import os

In [3]:
dir2='/content/drive/MyDrive/8thSemProject/botnet_dataset/device2/'
device2_df=pd.DataFrame()
i=0
for file in os.listdir(dir2+'gafgyt/'):
  df_file = pd.read_csv(os.path.join(dir2+'gafgyt/', file), encoding = 'ISO-8859-1',low_memory=False)
  df_file["label"]=i
  i=i+1
  device2_df=pd.concat([device2_df, df_file])
for file in os.listdir(dir2+'mirai/'):
  df_file = pd.read_csv(os.path.join(dir2+'mirai/', file), encoding = 'ISO-8859-1',low_memory=False)
  df_file["label"]=i
  i=i+1
  device2_df=pd.concat([device2_df, df_file])
df_file=pd.read_csv('/content/drive/MyDrive/8thSemProject/botnet_dataset/device2/benign.csv')
df_file['label']=i
device2_df=pd.concat([device2_df, df_file])

In [4]:
temp_df=device2_df

In [5]:
x=temp_df.drop(['label'],axis=1)
y=temp_df['label']
normalized_df=(x-x.mean())/x.std()


In [6]:
from sklearn.model_selection import train_test_split
import numpy as np
X_train, X_test, y_train, y_test = train_test_split(normalized_df, y, test_size=0.20, random_state=0)
y_train = np.array(y_train)

In [7]:
from  sklearn.linear_model import SGDClassifier, LinearRegression
from sklearn import metrics
lr = SGDClassifier(loss="log", penalty="l2", max_iter=200)
st=time.time()
lr.fit(X_train, y_train)
en=time.time()
print(en-st)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:163: FutureWarning: The loss 'log' was deprecated in v1.1 and will be removed in version 1.3. Use `loss='log_loss'` which is equivalent.
  warnings.warn(


92.4906702041626


In [8]:
y_pred = lr.predict(X_test)
print("Stochastic Gradient Descent\nAccuracy =", metrics.accuracy_score(y_test, y_pred)*100)

Stochastic Gradient Descent
Accuracy = 83.54189596592812


In [9]:
from sklearn import metrics
from sklearn.metrics import f1_score
print('Stochastic Gradient Descent')

print('Accuracy = ', metrics.accuracy_score(y_test, y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None,
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred,
                                                                 labels=None,
                                                                 target_names=None,
                                                                 sample_weight=None,
                                                                 digits=2,
                                                                 output_dict=False))

print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

Stochastic Gradient Descent
Accuracy =  83.54189596592812
Confusion Matrix =
 [[ 8622  1929     5     0     0     0     0    14   173     0     0]
 [ 2705  3117     6     0     0     0     0     1   108     0     0]
 [   10     0  4956     0     0     1     0     0   572     0     4]
 [    0     0     0 18881     0     0     0     0     0     6    12]
 [    1     0    11 20928     1     4     0     0     3     1     2]
 [    0     0     0     0     0 22174     0     0   485    66     0]
 [    0     0   191     0     2     0  8382    38     6     0     1]
 [    0     3     1     0     1     0     1 23483     3     0     0]
 [    0     0     0     0     1    18     1     0 30228    22     0]
 [    0     0     0     0     0    21     0     0   142 17193     0]
 [    0     0     2     0     1     0     0     0    12     0  2625]]
Recall = 0.8354189596592813
Classification Report =
               precision    recall  f1-score   support

           0       0.76      0.80      0.78     10743


In [10]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
st1=time.time()
model.fit(X_train, y_train)
en1=time.time()
print(en1-st1)

2.693997383117676


In [11]:
pred = model.predict(X_test)

In [12]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('Naive Bayes')

print('Accuracy = ', metrics.accuracy_score(y_test, pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None,
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred,
                                                                 labels=None,
                                                                 target_names=None,
                                                                 sample_weight=None,
                                                                  digits=2,
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

Naive Bayes
Accuracy =  72.29267358951046
Confusion Matrix =
 [[ 8622  1929     5     0     0     0     0    14   173     0     0]
 [ 2705  3117     6     0     0     0     0     1   108     0     0]
 [   10     0  4956     0     0     1     0     0   572     0     4]
 [    0     0     0 18881     0     0     0     0     0     6    12]
 [    1     0    11 20928     1     4     0     0     3     1     2]
 [    0     0     0     0     0 22174     0     0   485    66     0]
 [    0     0   191     0     2     0  8382    38     6     0     1]
 [    0     3     1     0     1     0     1 23483     3     0     0]
 [    0     0     0     0     1    18     1     0 30228    22     0]
 [    0     0     0     0     0    21     0     0   142 17193     0]
 [    0     0     2     0     1     0     0     0    12     0  2625]]
Recall = 0.8354189596592813
Classification Report =
               precision    recall  f1-score   support

           0       0.76      0.80      0.78     10743
           1    

In [13]:
from sklearn.ensemble import AdaBoostClassifier
import warnings
warnings.filterwarnings("ignore")

In [14]:
X_train, X_val, Y_train, Y_val = train_test_split(x, y, test_size=0.20, random_state=28)

In [15]:
adb = AdaBoostClassifier()
st=time.time()
adb_model = adb.fit(X_train,Y_train)
en=time.time()
print(en-st)

546.0021228790283


In [16]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('Adaboost')

print('Accuracy = ', metrics.accuracy_score(y_test, pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None,
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred,
                                                                 labels=None,
                                                                 target_names=None,
                                                                 sample_weight=None,
                                                                  digits=2,
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

Adaboost
Accuracy =  72.29267358951046
Confusion Matrix =
 [[ 8622  1929     5     0     0     0     0    14   173     0     0]
 [ 2705  3117     6     0     0     0     0     1   108     0     0]
 [   10     0  4956     0     0     1     0     0   572     0     4]
 [    0     0     0 18881     0     0     0     0     0     6    12]
 [    1     0    11 20928     1     4     0     0     3     1     2]
 [    0     0     0     0     0 22174     0     0   485    66     0]
 [    0     0   191     0     2     0  8382    38     6     0     1]
 [    0     3     1     0     1     0     1 23483     3     0     0]
 [    0     0     0     0     1    18     1     0 30228    22     0]
 [    0     0     0     0     0    21     0     0   142 17193     0]
 [    0     0     2     0     1     0     0     0    12     0  2625]]
Recall = 0.8354189596592813
Classification Report =
               precision    recall  f1-score   support

           0       0.76      0.80      0.78     10743
           1       

In [17]:
import re
df = temp_df.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

In [18]:
x=df.drop(['label'],axis=1)
y=df['label']

In [19]:
X_train, X_val, Y_train, Y_val = train_test_split(x, y, test_size=0.20, random_state=28)

In [20]:
import lightgbm as lgb
clf = lgb.LGBMClassifier()
st=time.time()
clf.fit(X_train, y_train)
en=time.time()
print(en-st)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.371749 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 28768
[LightGBM] [Info] Number of data points in the train set: 668700, number of used features: 115
[LightGBM] [Info] Start training from score -2.761282
[LightGBM] [Info] Start training from score -3.311778
[LightGBM] [Info] Start training from score -3.416523
[LightGBM] [Info] Start training from score -2.172998
[LightGBM] [Info] Start training from score -2.076425
[LightGBM] [Info] Start training from score -1.999323
[LightGBM] [Info] Start training from score -2.962291
[LightGBM] [Info] Start training from score -1.969355
[LightGBM] [Info] Start training from score -1.707803
[LightGBM] [Info] Start training from score -2.256669
[LightGBM] [Info] Start training from score -4.156535
198.0152871608734


In [21]:
y_pred=clf.predict(X_test)

In [22]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('lightbgm')

print('Accuracy = ', metrics.accuracy_score(y_test, pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None,
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None,
                                             pos_label=1, average='weighted',
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred,
                                                                 labels=None,
                                                                 target_names=None,
                                                                 sample_weight=None,
                                                                  digits=2,
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

lightbgm
Accuracy =  72.29267358951046
Confusion Matrix =
 [[    0     0     0     0     0     0     0     0 10743     0     0]
 [    0     0     0     3     0     0     1     0  5933     0     0]
 [    0    23     0  1879     0     0     6     0  3635     0     0]
 [    0     1     0 18881     0     0     0     0    17     0     0]
 [    0     0     0 20931     0     0     0     0    19     0     1]
 [    0   306     0  2947     0     0     0     0 19472     0     0]
 [    0     0     0  8566     0     0     0     0    54     0     0]
 [    0     0     0  5363     0     0     0     0 18129     0     0]
 [    0   533     0  4777     0     0     0     0 24960     0     0]
 [    0   121     0  2298     0     0     0     0 14937     0     0]
 [    0     4     1     3     2     0   710     0  1608     4   308]]
Recall = 0.2640869502799445
Classification Report =
               precision    recall  f1-score   support

           0       0.00      0.00      0.00     10743
           1       